
export TC_SCRIPTS_HOME=$HOME/src/ihg/buildScripts

export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad
export PATH=/usr/local/bin:/usr/local/sbin:$PATH:/usr/local/mysql/bin:$TC_SCRIPTS_HOME/bin:$HOME/bin:$HOME/apps/maven/bin

export JAVA_VERSION="1.7"
#export JAVA_HOME=`/usr/libexec/java_home -v $JAVA_VERSION`
if [[ -d /Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home ]]; then
  export JAVA_HOME="/Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home"
else
  export JAVA_HOME="/opt/jdk1.7.0_79"
fi

export JVM_ARGS="-Xms1024m -Xmx1024m"
export MAVEN_OPTS="-Xmx1024m -XX:MaxPermSize=512m"


switchJava() {
   if [[ $JAVA_VERSION == "1.7" ]]; then
      export JAVA_VERSION="1.8"
      export MAVEN_OPTS="-Xmx1024m"
      export JAVA_HOME=`/usr/libexec/java_home -v $JAVA_VERSION`
   elif [[ $JAVA_VERSION == "1.8" ]]; then
      export JAVA_VERSION="9"
      export MAVEN_OPTS="-Xmx1024m"
      export JAVA_HOME=`/usr/libexec/java_home -v $JAVA_VERSION`
   else
      export JAVA_VERSION="1.7"
      export MAVEN_OPTS="-Xmx1024m -XX:MaxPermSize=512m"
      export JAVA_HOME=`/usr/libexec/java_home -v $JAVA_VERSION`
   fi
   echo "Switching to java $JAVA_VERSION"
}
export STUDIO_JDK=$JAVA_HOME

export TTY=`tty`


export PYTHONPATH=/usr/local/lib/python2.7/site-packages:/opt/local/lib/python2.7/site-packages:$PYTHONPATH

export LOLCOMMITS_FORK=1
export LOLCOMMITS_DELAY=4
export LOLCOMMITS_ANIMATE=3

if [[ -f $HOME/.zsh/github_token.txt ]]; then
    export HOMEBREW_GITHUB_API_TOKEN=`cat $HOME/.zsh/github_token.txt`
fi

if [[ -f ~/perl5/perlbrew/etc/bashrc ]]; then
   source ~/perl5/perlbrew/etc/bashrc
fi

#. $HOME/src/powerline/powerline/bindings/zsh/powerline.zsh

# set -o vi
bindkey -v
export KEYTIMEOUT=1

typeset -Ag FX FG BG

zle-keymap-select () {
  if [[ $KEYMAP = vicmd ]]; then
    echo -ne "\e[\x32 q"
  else
    echo -ne "\e[\x36 q"
  fi
}

zle-line-init () {
  echo -ne "\e[\x36 q"
}

zle -N zle-keymap-select
zle -N zle-line-init

bindkey "^R" history-incremental-search-backward
bindkey "^?" backward-delete-char
bindkey "^W" backward-kill-word
bindkey "^H" backward-delete-char
bindkey "^U" backward-kill-line

HISTSIZE=3000
if (( ! EUID )); then
  HISTFILE=~/.history_root
else
  HISTFILE=~/.history
fi
SAVEHIST=3000
setopt SHARE_HISTORY
setopt EXTENDED_HISTORY

source $HOME/.zsh/prompt.zsh
fpath=(/usr/local/share/zsh-completions $fpath)

autoload -U compinit
compinit

source $HOME/.zsh/aws_zsh_completer.sh

which gls 2>&1 > /dev/null
if [[ $? = 0 ]]; then
  alias ls="ls --color=auto"
  alias ll="ls --color=auto -Alh"
else
  alias ls="ls -G"
  alias ll="ls -G -Alh"
fi
alias ..="cd .."
alias grep="grep --color=auto"
alias egrep="egrep --color=auto"
alias gs="git status"
alias gd="git diff"
alias gits="git"
alias "git clean"="git clean -i"


which mvim 2>&1 > /dev/null
HAS_MVIM_EXIT_CODE=$?
which gvim 2>&1 > /dev/null
HAS_GVIM_EXIT_CODE=$?
if [[ $SSH_TTY =~ /dev/.* ]]; then
  IS_SSH=1
  export EDITOR="vim"
elif [[ $HAS_MVIM_EXIT_CODE = 0 ]]; then
  alias gvim="mvim -f"
  export EDITOR="mvim -f"
  alias vim=$EDITOR
elif [[ $HAS_GVIM_EXIT_CODE = 0 ]]; then
  export EDITOR="gvim -f"
  alias vim=$EDITOR
fi


if [ -f $HOME/.sdkman/bin/sdkman-init.sh ]; then
   source ~/.sdkman/bin/sdkman-init.sh
fi

which rbenv 2>&1 > /dev/null
if [ $? = 0 ]; then
   eval "$(rbenv init -)"
fi

if [ -f /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh ]; then
   source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh
fi
