
export TC_SCRIPTS_HOME=$HOME/src/ihg/buildScripts

export CLICOLOR=1
export LSCOLORS=ExFxCxDxBxegedabagacad
export PATH=/usr/local/bin:/usr/local/sbin:$PATH:/usr/local/mysql/bin:/opt/local/bin:$TC_SCRIPTS_HOME/bin


export JAVA_HOME=`/usr/libexec/java_home -v 1.7`
export JVM_ARGS="-Xms1024m -Xmx1024m -XX:MaxPermSize=512m"

export TTY=`tty`


export PYTHONPATH=/usr/local/lib/python2.7/site-packages:/opt/local/lib/python2.7/site-packages:$PYTHONPATH

export LOLCOMMITS_FORK=1
export LOLCOMMITS_DELAY=4
export LOLCOMMITS_ANIMATE=3

export HOMEBREW_GITHUB_API_TOKEN=9c6118c34ee1ea312c2617fe79c75b4ac0d5f815

export MAVEN_OPTS="-Xmx1024m -XX:MaxPermSize=512m"

source ~/perl5/perlbrew/etc/bashrc

#. $HOME/src/powerline/powerline/bindings/zsh/powerline.zsh

# set -o vi
bindkey -v

typeset -Ag FX FG BG

zle-keymap-select () {
  if [[ $KEYMAP = vicmd ]]; then
    echo -ne "\e[\x32 q"
  else
    echo -ne "\e[\x36 q"
  fi
}

zle-line-init () {
  echo -ne "\e[\x36 q"
}

zle -N zle-keymap-select
zle -N zle-line-init

bindkey "^R" history-incremental-search-backward
HISTSIZE=1000
if (( ! EUID )); then
  HISTFILE=~/.history_root
else
  HISTFILE=~/.history
fi
SAVEHIST=1000
setopt SHARE_HISTORY
setopt EXTENDED_HISTORY

source $HOME/.zsh/prompt.zsh

autoload -U compinit
compinit

alias ls="gls --color=auto"
alias ll="gls --color=auto -Alh"
alias ..="cd .."
alias grep="grep --color=auto"
alias egrep="egrep --color=auto"
alias gs="git status"
alias gd="git diff"
alias gits="git"

if [[ $SSH_TTY =~ /dev/.* ]]
then
  IS_SSH=1
  export EDITOR="vim"
else
  alias gvim="mvim -f"
  export EDITOR="mvim -f"
  alias vim=$EDITOR
fi


if [ -f $HOME/.gvm/bin/gvm-init.sh ]; then
   source ~/.gvm/bin/gvm-init.sh
fi

which rbenv 2>&1 > /dev/null
if [ $? = 0 ]; then
   eval "$(rbenv init -)"
fi
