set bg=dark
set guioptions+=T
"set guifont=Source\ Code\ Pro\ for\ Powerline:h22
"set guifont=Knack\ Regular\ Nerd\ Font\ Complete:h16
set guifont=DankMonoNerdFontComplete-Regular:h16
set lines=40
set columns=100
set nu

let g:html_use_css=1

"colorscheme macvim
"colorscheme leo
"colorscheme morning
"colorscheme github
"colorscheme solarized
color dracula

"au VimLeave * call system('echo -e -n "\033]50;StealFocus\007">/dev/tty')
"au VimLeave * call system('echo hello world '.$TTY.'>'.$TTY)
au VimLeave * call system('echo -e -n "\033]50;StealFocus\007">'.$TTY)
" end nerdtree commands

