syntax on
filetype plugin indent on

" Convert tabs to spaces
set expandtab
" tabs are worth 3 spaces
set shiftwidth=2
set tabstop=2
set softtabstop=2

set shell=/bin/bash

" automatically indent
" in code blocks
set smartindent

highlight WhiteOnRed ctermfg=white ctermbg=red

highlight ColorColumn ctermbg=magenta
call matchadd('ColorColumn', '\%81v', 100)

" Change the bad chars to use unicode chars
exec "set listchars=tab:\uBB\uBB,trail:\uB7,nbsp:~"
set list


set backspace=2
set nocompatible
set ruler
set showmode

" make semicolon also work as colon for commands
nnoremap ; :



" TODO 2021-01-05 find out what this viminfo does
"set viminfo='10,\"100,:20,%,n~/.viminfo

"hilight searches in LightBlue
"This comes from Damian Conway's .vimrc
set hlsearch
hi Search guibg=LightBlue

" This rewires n and N to do the highlighing...
nnoremap <silent> n   n:call HLNext(0.4)<cr>
nnoremap <silent> N   N:call HLNext(0.4)<cr>

" remap semicolon

nnoremap ; :



" 2021-01-05 Disabling this section - I don't know what it does
" au BufReadPost * if line("'\"") > 0|if line("'\"") <= line("$")|exe("norm '\"")|else|exe "norm $"|endif|endif
" au BufNewFile,BufRead *.txtmt setf mathdoc

au BufRead /private/var/folders/*/sql* set ft=mysql

" nerdtree commands
function OpenMe()
  NERDTree
  wincmd l
endfunction
function CloseMe()
  call system('echo -e -n "\033]50;StealFocus\007">/dev/tty')
  q
endfunction


"set rtp+=/usr/local/lib/python2.7/site-packages/Powerline-beta-py2.7.egg/powerline/bindings/vim


" 2021-01-05 - I don't work with spin files anymore
" au BufRead,BufNewFile *.spin set filetype=spin
" au! Syntax spin source $HOME/.vim/syntax/spin.vim


au BufRead,BufNewFile *.json set filetype=json foldmethod=syntax
au BufRead,BufNewFile *.jsonl set filetype=jsonl
"au! Syntax spin source $HOME/.vim/syntax/json.vim
au BufRead,BufNewFile *.tt set filetype=tt2html
au BufRead,BufNewFile *.t set filetype=tt2html
au BufRead,BufNewFile *.jad set filetype=java
au BufRead,BufNewFile *.class silent set filetype=class
au BufRead,BufNewFile *.dtrace setf dtrace
au BufRead,BufNewFile *.dtruss setf dtrace


"set autoindent
let perl_includes_pod = 1
let perl_extended_vars = 1

autocmd FileType perl set makeprg=perl\ -c\ %\ $*
autocmd FileType perl set errorformat=%f:%l:%m
autocmd FileType perl set autowrite

let java_space_errors = 1

vmap <tab> >gv
vmap <s-tab> <gv

" Double-click to toggle fold
"nnoremap <2-LeftMouse> za

" Shift+space to toggle all folds under cursor
"nnoremap <S-space> zA

if isdirectory('/opt/homebrew')
  set rtp+=/opt/homebrew/opt/fzf
elseif isdirectory('/usr/local/opt')
  set rtp+=/usr/local/opt/fzf
endif

au FileType perl command! -range=% -nargs=* Tidy <line1>,<line2>! \perltidy
au FileType json command! -range=% -nargs=* Tidy call JsonTidy(<line1>,<line2>)
au FileType jsonl command! -range=% -nargs=* Tidy call JsonlTidy(<line1>,<line2>)
au FileType yaml command! -range=% -nargs=* Tidy call YamlTidy(<line1>,<line2>)
au FileType xml command! -range=% -nargs=* Tidy call XmlTidy(<line1>,<line2>)

"TODO use a proper javascript beautifier for this
" au FileType javascript command! -range=% -nargs=* Tidy <line1>,<line2>! /Users/gordon/src/js-beautify/python/js-beautify -s 2 -

augroup filetypedetect

let mapleader=","
au FileType javascript command Dash call SearchDash('javascript:')
au FileType vim command Dash call SearchDash('vim:')
au FileType perl command Dash call SearchDash('perl:')
au FileType ruby command Dash call SearchDash('ruby:')


map <leader>d :Dash<cr>
function SearchDash(lib)
  let s:url = "dash://".a:lib.expand("<cword>")
  execute "silent ! /usr/bin/open ".s:url
  redraw!
endfunction

function JsonTidy(line1,line2)
  let text = join(getline(a:line1, a:line2),'')
  let text = substitute(text,"'\([^']*\)'",'"\1"','g')
  let text = substitute(text,"\(, \|{\)\([a-zA-Z_]*\):",'\1"\2":','g')
  let text = substitute(text,', }',' }','g')
  let tempfile = substitute(system("mktemp /tmp/vimtidy.XXXX"),'\n','','')
  call writefile([text],tempfile)
  execute a:line1.",".a:line2." ! cat ".tempfile." | node ~/.vim/json_tidy.js"
  call system("rm ".tempfile)
endfunction

function JsonlTidy(line1,line2)
  let lines = getline(a:line1, a:line2)
  let output = []

  for line in lines
    " Skip empty lines
    if line =~ '^\s*$'
      continue
    endif

    " Format each JSON line
    let tempfile = substitute(system("mktemp /tmp/vimtidy.XXXX"),'\n','','')
    call writefile([line],tempfile)
    let formatted = system("cat ".tempfile." | node ~/.vim/json_tidy.js")
    call system("rm ".tempfile)

    " Remove trailing newline from formatted output
    let formatted = substitute(formatted, '\n$', '', '')

    " Add the formatted JSON to output
    let output += split(formatted, '\n')

    " Add blank line separator
    call add(output, '')
  endfor

  " Remove the final blank line if it exists
  if len(output) > 0 && output[-1] == ''
    call remove(output, -1)
  endif

  " Replace the range with formatted output
  execute a:line1.",".a:line2."delete"
  call append(a:line1 - 1, output)
endfunction

function YamlTidy(line1,line2)
  let text = join(getline(a:line1, a:line2),'')
  " let text = substitute(text,"'\([^']*\)'",'"\1"','g')
  " let text = substitute(text,"\(, \|{\)\([a-zA-Z_]*\):",'\1"\2":','g')
  " let text = substitute(text,', }',' }','g')
  let tempfile = substitute(system("mktemp /tmp/vimtidy.XXXX"),'\n','','')
  call writefile([text],tempfile)
  execute a:line1.",".a:line2." ! cat ".tempfile." | node ~/.vim/yaml_tidy.js"
  call system("rm ".tempfile)
endfunction

function XmlTidy(line1,line2)
	let text = [join(getline(a:line1, a:line2),'')]
        let tempfile = substitute(system("mktemp /tmp/vimtidy.XXXX"),'\n','','')
        call writefile(text,tempfile)
	execute a:line1.",".a:line2." ! perl -MXML::Tidy -e '$tidy=XML::Tidy->new(shift());$tidy->tidy();print $tidy->toString();' ".tempfile
        call system("rm ".tempfile)
endfunction

map Q :q

"colorscheme torte
"colorscheme morning
set laststatus=2

" JSON path function for statusline
function! GetJsonPath()
  if &filetype != 'json'
    return ''
  endif
  
  let line = getline('.')
  let col = col('.')
  let lnum = line('.')
  
  " Find all opening braces/brackets before current position
  let path = []
  let brace_stack = []
  let in_string = 0
  let in_key = 0
  let current_key = ''
  
  " Go through each line from start to current position
  for l in range(1, lnum)
    let text = getline(l)
    if l == lnum
      let text = strpart(text, 0, col - 1)
    endif
    
    let i = 0
    while i < len(text)
      let char = text[i]
      
      " Handle string detection
      if char == '"' && (i == 0 || text[i-1] != '\')
        let in_string = !in_string
        if in_string
          let current_key = ''
          let in_key = 1
        elseif in_key
          let in_key = 0
        endif
      elseif in_string && in_key
        let current_key .= char
      elseif !in_string
        if char == '{'
          call add(brace_stack, {'type': 'object', 'key': ''})
        elseif char == '['
          call add(brace_stack, {'type': 'array', 'index': -1})
        elseif char == ':'
          if len(brace_stack) > 0 && brace_stack[-1]['type'] == 'object'
            let brace_stack[-1]['key'] = current_key
          endif
        elseif char == ',' || char == '}'
          if len(brace_stack) > 0 && brace_stack[-1]['type'] == 'array'
            let brace_stack[-1]['index'] += 1
          endif
        elseif char == '}' || char == ']'
          if len(brace_stack) > 0
            call remove(brace_stack, -1)
          endif
        endif
      endif
      let i += 1
    endwhile
  endfor
  
  " Build path string
  let path_parts = []
  for item in brace_stack
    if item['type'] == 'object' && item['key'] != ''
      call add(path_parts, item['key'])
    elseif item['type'] == 'array'
      call add(path_parts, '[' . max([0, item['index']]) . ']')
    endif
  endfor
  
  return len(path_parts) > 0 ? '.' . join(path_parts, '.') : ''
endfunction

function! HLNext (blinktime)
  let [bufnum, lnum, col, off] = getpos('.')
  let matchlen = strlen(matchstr(strpart(getline('.'),col-1),@/))
  let target_pat = '\c\%#'.@/
  let blinks = 3
  for n in range(1, blinks)
    let red = matchadd('WhiteOnRed', target_pat, 101)
    redraw
    exec 'sleep ' . float2nr(a:blinktime / (2*blinks) * 1000) . 'm'
    call matchdelete(red)
    redraw
    exec 'sleep ' . float2nr(a:blinktime / (2*blinks) * 1000) . 'm'
  endfor
endfunction


filetype off

" Use vim-plug instead of Vundle
call plug#begin('~/.vim/plugged')

" Plugins
Plug 'dracula/vim'
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

" GraphQL syntax highlighting
Plug 'jparise/vim-graphql'

" Language and config file syntax
Plug 'chr4/nginx'
Plug 'dag/vim-fish'
Plug 'udalov/kotlin-vim'

" Old plugins (L9, FuzzyFinder) - keep only if you really use them
Plug 'vim-scripts/L9'
Plug 'vim-scripts/FuzzyFinder'

" JSON highlighting
Plug 'elzr/vim-json'

" GitHub Copilot
Plug 'github/copilot.vim'

call plug#end()


filetype plugin indent on

if has("gui_vimr")
  " VimR specific stuff
  set bg=dark
  set guifont=
  set lines=40
  set columns=100
  set nu

  color dracula

  "au VimLeave * call system('echo -e -n "\033]50;StealFocus\007">'.$TTY)
  "au VimLeave * call system('echo -e -n "\033]50;StealFocus\007">'.$DISPLAY)
endif

if has("gui_macvim")
  " MacVim specific stuff
  set bg=dark
  set guioptions+=T

  set lines=40
  set columns=100
  set nu
  set guifont=JetBrainsMono\ Nerd\ Font:h14

  let g:html_use_css=1

  color dracula

  "au VimLeave * call system('echo -e -n "\033]50;StealFocus\007">'.$TTY)
endif

if exists("g:neovide")
  " Neovide specific stuff
  set bg=dark
  set guioptions+=T

  set lines=40
  set columns=100
  set nu
  set guifont=JetBrainsMono\ Nerd\ Font:h14  

  let g:html_use_css=1

  "nmap <D-v> "+p
  " Paste without formatting
  imap <D-v> <ESC>:set paste<CR>"+p:set nopaste<CR>i
  cmap <D-v> <C-R>+
  vmap <D-v> "+p

  " CMD+C to copy to clipboard
  vmap <D-c> "+y
  " CMD+X to cut to clipboard
  vmap <D-x> "+x
  " Select all
  nmap <D-a> gg<S-v>G

  let g:neovide_cursor_animation_length = 0
  let g:neovide_cursor_trail_size = 0
"  let g:neovide_cursor_antialiasing = v:false
  let g:neovide_cursor_animate_in_insert_mode = v:false
  let g:neovide_cursor_animate_command_line = v:false
"  let g:neovide_cursor_vfx_mode = ""
  let g:neovide_scroll_animation_length = 0
"  let g:neovide_floating_blur_amount_x = 0
"  let g:neovide_floating_blur_amount_y = 0
  let g:neovide_ligatures = v:false

  set shada='10,\"100,:20,%,n~/.local/share/nvim/shada/main.shada

  au VimLeave * sleep 100m | call system('echo -e -n "\033]50;StealFocus\007">' . $TTY)

  " Jump to last position when reopening a file
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

  color dracula
endif
