syntax on
filetype plugin indent on

" Convert tabs to spaces
set expandtab
" tabs are worth 3 spaces
set shiftwidth=2
set tabstop=2
set softtabstop=2

set shell=/bin/bash

" automatically indent
" in code blocks
set smartindent

highlight WhiteOnRed ctermfg=white ctermbg=red

highlight ColorColumn ctermbg=magenta
call matchadd('ColorColumn', '\%81v', 100)

" Change the bad chars to use unicode chars
exec "set listchars=tab:\uBB\uBB,trail:\uB7,nbsp:~"
set list


set backspace=2
set nocompatible
set ruler
set showmode

" make semicolon also work as colon for commands
nnoremap ; :



" TODO 2021-01-05 find out what this viminfo does
"set viminfo='10,\"100,:20,%,n~/.viminfo

"hilight searches in LightBlue
"This comes from Damian Conway's .vimrc
set hlsearch
hi Search guibg=LightBlue

" This rewires n and N to do the highlighing...
nnoremap <silent> n   n:call HLNext(0.4)<cr>
nnoremap <silent> N   N:call HLNext(0.4)<cr>

" remap semicolon

nnoremap ; :

" 2021-01-05 Disabling this section - I don't know what it does
" au BufReadPost * if line("'\"") > 0|if line("'\"") <= line("$")|exe("norm '\"")|else|exe "norm $"|endif|endif
" au BufNewFile,BufRead *.txtmt setf mathdoc

au BufRead /private/var/folders/*/sql* set ft=mysql

"set rtp+=/usr/local/lib/python2.7/site-packages/Powerline-beta-py2.7.egg/powerline/bindings/vim


" 2021-01-05 - I don't work with spin files anymore
" au BufRead,BufNewFile *.spin set filetype=spin
" au! Syntax spin source $HOME/.vim/syntax/spin.vim


au BufRead,BufNewFile *.json set filetype=json foldmethod=syntax
au BufRead,BufNewFile *.jsonl set filetype=jsonl
"au! Syntax spin source $HOME/.vim/syntax/json.vim
au BufRead,BufNewFile *.tt set filetype=tt2html
au BufRead,BufNewFile *.t set filetype=tt2html
au BufRead,BufNewFile *.jad set filetype=java
au BufRead,BufNewFile *.class silent set filetype=class
au BufRead,BufNewFile *.dtrace setf dtrace
au BufRead,BufNewFile *.dtruss setf dtrace


"set autoindent
let perl_includes_pod = 1
let perl_extended_vars = 1

autocmd FileType perl set makeprg=perl\ -c\ %\ $*
autocmd FileType perl set errorformat=%f:%l:%m
autocmd FileType perl set autowrite

let java_space_errors = 1

vmap <tab> >gv
vmap <s-tab> <gv

" Double-click to toggle fold
"nnoremap <2-LeftMouse> za

" Shift+space to toggle all folds under cursor
"nnoremap <S-space> zA

if isdirectory('/opt/homebrew')
  set rtp+=/opt/homebrew/opt/fzf
elseif isdirectory('/usr/local/opt')
  set rtp+=/usr/local/opt/fzf
endif

au FileType perl command! -range=% -nargs=* Tidy <line1>,<line2>! \perltidy
au FileType json command! -range=% -nargs=* Tidy call JsonTidy(<line1>,<line2>)
au FileType jsonl command! -range=% -nargs=* Tidy call JsonlTidy(<line1>,<line2>)
au FileType yaml command! -range=% -nargs=* Tidy call YamlTidy(<line1>,<line2>)
au FileType xml command! -range=% -nargs=* Tidy call XmlTidy(<line1>,<line2>)

"TODO use a proper javascript beautifier for this
" au FileType javascript command! -range=% -nargs=* Tidy <line1>,<line2>! /Users/gordon/src/js-beautify/python/js-beautify -s 2 -

augroup filetypedetect

let mapleader=","

function JsonTidy(line1,line2)
  let text = join(getline(a:line1, a:line2),'')
  let text = substitute(text,"'\([^']*\)'",'"\1"','g')
  let text = substitute(text,"\(, \|{\)\([a-zA-Z_]*\):",'\1"\2":','g')
  let text = substitute(text,', }',' }','g')
  let tempfile = substitute(system("mktemp /tmp/vimtidy.XXXX"),'\n','','')
  call writefile([text],tempfile)
  execute a:line1.",".a:line2." ! cat ".tempfile." | node ~/.vim/json_tidy.js"
  call system("rm ".tempfile)
endfunction

function JsonlTidy(line1,line2)
  let lines = getline(a:line1, a:line2)
  let output = []

  for line in lines
    " Skip empty lines
    if line =~ '^\s*$'
      continue
    endif

    " Format each JSON line
    let tempfile = substitute(system("mktemp /tmp/vimtidy.XXXX"),'\n','','')
    call writefile([line],tempfile)
    let formatted = system("cat ".tempfile." | node ~/.vim/json_tidy.js")
    call system("rm ".tempfile)

    " Remove trailing newline from formatted output
    let formatted = substitute(formatted, '\n$', '', '')

    " Add the formatted JSON to output
    let output += split(formatted, '\n')

    " Add blank line separator
    call add(output, '')
  endfor

  " Remove the final blank line if it exists
  if len(output) > 0 && output[-1] == ''
    call remove(output, -1)
  endif

  " Replace the range with formatted output
  execute a:line1.",".a:line2."delete"
  call append(a:line1 - 1, output)
endfunction

function YamlTidy(line1,line2)
  let text = join(getline(a:line1, a:line2),'')
  " let text = substitute(text,"'\([^']*\)'",'"\1"','g')
  " let text = substitute(text,"\(, \|{\)\([a-zA-Z_]*\):",'\1"\2":','g')
  " let text = substitute(text,', }',' }','g')
  let tempfile = substitute(system("mktemp /tmp/vimtidy.XXXX"),'\n','','')
  call writefile([text],tempfile)
  execute a:line1.",".a:line2." ! cat ".tempfile." | node ~/.vim/yaml_tidy.js"
  call system("rm ".tempfile)
endfunction

function XmlTidy(line1,line2)
	let text = [join(getline(a:line1, a:line2),'')]
        let tempfile = substitute(system("mktemp /tmp/vimtidy.XXXX"),'\n','','')
        call writefile(text,tempfile)
	execute a:line1.",".a:line2." ! perl -MXML::Tidy -e '$tidy=XML::Tidy->new(shift());$tidy->tidy();print $tidy->toString();' ".tempfile
        call system("rm ".tempfile)
endfunction

map Q :q

"colorscheme torte
"colorscheme morning
set laststatus=2

" JSON path function for statusline
function! GetJsonPath()
  if &filetype != 'json'
    return ''
  endif
  
  let line = getline('.')
  let col = col('.')
  let lnum = line('.')
  
  " Find all opening braces/brackets before current position
  let path = []
  let brace_stack = []
  let in_string = 0
  let in_key = 0
  let current_key = ''
  
  " Go through each line from start to current position
  for l in range(1, lnum)
    let text = getline(l)
    if l == lnum
      let text = strpart(text, 0, col - 1)
    endif
    
    let i = 0
    while i < len(text)
      let char = text[i]
      
      " Handle string detection
      if char == '"' && (i == 0 || text[i-1] != '\')
        let in_string = !in_string
        if in_string
          let current_key = ''
          let in_key = 1
        elseif in_key
          let in_key = 0
        endif
      elseif in_string && in_key
        let current_key .= char
      elseif !in_string
        if char == '{'
          call add(brace_stack, {'type': 'object', 'key': ''})
        elseif char == '['
          call add(brace_stack, {'type': 'array', 'index': -1})
        elseif char == ':'
          if len(brace_stack) > 0 && brace_stack[-1]['type'] == 'object'
            let brace_stack[-1]['key'] = current_key
          endif
        elseif char == ',' || char == '}'
          if len(brace_stack) > 0 && brace_stack[-1]['type'] == 'array'
            let brace_stack[-1]['index'] += 1
          endif
        elseif char == '}' || char == ']'
          if len(brace_stack) > 0
            call remove(brace_stack, -1)
          endif
        endif
      endif
      let i += 1
    endwhile
  endfor
  
  " Build path string
  let path_parts = []
  for item in brace_stack
    if item['type'] == 'object' && item['key'] != ''
      call add(path_parts, item['key'])
    elseif item['type'] == 'array'
      call add(path_parts, '[' . max([0, item['index']]) . ']')
    endif
  endfor
  
  return len(path_parts) > 0 ? '.' . join(path_parts, '.') : ''
endfunction

function! HLNext (blinktime)
  let [bufnum, lnum, col, off] = getpos('.')
  let matchlen = strlen(matchstr(strpart(getline('.'),col-1),@/))
  let target_pat = '\c\%#'.@/
  let blinks = 3
  for n in range(1, blinks)
    let red = matchadd('WhiteOnRed', target_pat, 101)
    redraw
    exec 'sleep ' . float2nr(a:blinktime / (2*blinks) * 1000) . 'm'
    call matchdelete(red)
    redraw
    exec 'sleep ' . float2nr(a:blinktime / (2*blinks) * 1000) . 'm'
  endfor
endfunction


filetype off

" Use vim-plug instead of Vundle
call plug#begin('~/.vim/plugged')
" Install plugins using :PlugInstall command in vim after adding them here

" Plugins
Plug 'dracula/vim'

" GraphQL syntax highlighting
Plug 'jparise/vim-graphql'

" Language and config file syntax
Plug 'chr4/nginx'
Plug 'dag/vim-fish'
Plug 'udalov/kotlin-vim'

" Old plugins (L9, FuzzyFinder) - keep only if you really use them
Plug 'vim-scripts/L9'
Plug 'vim-scripts/FuzzyFinder'

" Language Server Protocol support
Plug 'neoclide/coc.nvim', {'branch': 'release'}

" JSON highlighting
Plug 'elzr/vim-json'

" GitHub Copilot
Plug 'github/copilot.vim'

" File navigation
Plug 'nvim-neo-tree/neo-tree.nvim', {'branch': 'v3.x'}
Plug 'MunifTanjim/nui.nvim'

" Editing enhancements
Plug 'tpope/vim-surround'
Plug 'tpope/vim-commentary'

" Git integration
Plug 'tpope/vim-fugitive'

" Modern Neovim plugins
Plug 'nvim-lua/plenary.nvim'
Plug 'nvim-tree/nvim-web-devicons'
Plug 'nvim-treesitter/nvim-treesitter', {'do': ':TSUpdate'}
Plug 'nvim-treesitter/nvim-treesitter-textobjects'
Plug 'nvim-telescope/telescope.nvim', {'branch': '0.1.x'}
Plug 'nvim-telescope/telescope-fzf-native.nvim', {'do': 'make'}
Plug 'nvim-lualine/lualine.nvim'
Plug 'lewis6991/gitsigns.nvim'
Plug 'folke/which-key.nvim'
Plug 'lukas-reineke/indent-blankline.nvim'
Plug 'windwp/nvim-autopairs'
Plug 'akinsho/bufferline.nvim', {'tag': '*'}
Plug 'folke/flash.nvim'
Plug 'folke/trouble.nvim'
Plug 'folke/todo-comments.nvim'

call plug#end()

" ============================================================================
" Plugin Configurations
" ============================================================================

" GitHub Copilot - use Homebrew node instead of asdf
let g:copilot_node_command = "/opt/homebrew/bin/node"

" Neo-tree
nnoremap <leader>n <cmd>Neotree toggle<CR>
nnoremap <leader>f <cmd>Neotree reveal<CR>

" Preferred editor window width
let g:editor_width=100
let g:neotree_width=35

" Auto-open Neo-tree in git repositories
function AutoNeoTree()
  if argc() == 0 && isdirectory('.git')
    execute 'set columns=' . (g:editor_width + g:neotree_width)
    Neotree show
  elseif argc() == 1 && isdirectory(argv()[0])
    execute 'set columns=' . (g:editor_width + g:neotree_width)
    execute 'Neotree show dir=' . argv()[0]
  else
    execute 'set columns=' . (g:editor_width)
  endif
endfunction

" Telescope
nnoremap <C-p> <cmd>Telescope find_files<CR>
nnoremap <leader>b <cmd>Telescope buffers<CR>
nnoremap <leader>r <cmd>Telescope live_grep<CR>
nnoremap <leader>h <cmd>Telescope oldfiles<CR>
nnoremap <leader>/ <cmd>Telescope current_buffer_fuzzy_find<CR>

" gitsigns keybindings are configured in the lua section below
set updatetime=100

" Bufferline tab navigation
nnoremap <S-l> <cmd>BufferLineCycleNext<CR>
nnoremap <S-h> <cmd>BufferLineCyclePrev<CR>
nnoremap <leader>x <cmd>bdelete<CR>

" vim-fugitive
nnoremap <leader>gb :Git blame<CR>
nnoremap <leader>gd :Gdiff<CR>
nnoremap <leader>gl :Git log<CR>

filetype plugin indent on

" ============================================================================
" Lua Plugin Configuration (Neovim only)
" ============================================================================
if has('nvim')
lua << EOF
local function safe_setup(name, config)
  local ok, mod = pcall(require, name)
  if ok then
    if type(config) == 'function' then
      config(mod)
    elseif config then
      mod.setup(config)
    end
  end
end

-- Treesitter: Better syntax highlighting that understands code structure
safe_setup('nvim-treesitter.configs', function(ts)
  ts.setup({
    ensure_installed = {
      'bash', 'css', 'fish', 'graphql', 'html', 'javascript', 'json',
      'kotlin', 'lua', 'markdown', 'perl', 'python', 'ruby', 'typescript',
      'vim', 'vimdoc', 'yaml',
    },
    highlight = { enable = true },
    indent = { enable = true },
    textobjects = {
      select = {
        enable = true,
        lookahead = true,
        keymaps = {
          ['af'] = '@function.outer',
          ['if'] = '@function.inner',
          ['ac'] = '@class.outer',
          ['ic'] = '@class.inner',
        },
      },
      move = {
        enable = true,
        set_jumps = true,
        goto_next_start = { [']m'] = '@function.outer' },
        goto_previous_start = { ['[m'] = '@function.outer' },
      },
    },
  })
end)

-- Telescope: Fuzzy finder for everything
safe_setup('telescope', function(telescope)
  telescope.setup({
    defaults = {
      file_ignore_patterns = { 'node_modules', '.git/' },
    },
  })
  pcall(telescope.load_extension, 'fzf')
end)

-- Lualine: Modern statusline with powerline separators
safe_setup('lualine', {
  options = {
    theme = 'dracula',
    icons_enabled = true,
  },
  sections = {
    lualine_a = { 'mode' },
    lualine_b = { 'branch', 'diff', 'diagnostics' },
    lualine_c = { 'filename' },
    lualine_x = { 'encoding', 'fileformat', 'filetype' },
    lualine_y = { 'progress' },
    lualine_z = { 'location' },
  },
})

-- Gitsigns: Git integration in the sign column
safe_setup('gitsigns', {
  on_attach = function(bufnr)
    local gs = package.loaded.gitsigns
    local function map(mode, l, r, opts)
      opts = opts or {}
      opts.buffer = bufnr
      vim.keymap.set(mode, l, r, opts)
    end
    map('n', ']c', function() gs.nav_hunk('next') end, { desc = 'Next hunk' })
    map('n', '[c', function() gs.nav_hunk('prev') end, { desc = 'Previous hunk' })
    map('n', '<leader>gs', gs.stage_hunk, { desc = 'Stage hunk' })
    map('n', '<leader>gu', gs.reset_hunk, { desc = 'Reset hunk' })
    map('n', '<leader>gB', function() gs.blame_line({ full = true }) end, { desc = 'Blame line' })
  end,
})

-- Neo-tree: File tree sidebar
safe_setup('neo-tree', function(neotree)
  neotree.setup({
    window = {
      width = 35,
      mappings = {
        ['<space>'] = 'toggle_node',
      },
    },
    filesystem = {
      filtered_items = {
        hide_dotfiles = false,
        hide_gitignored = false,
        hide_by_name = { '.git', '.DS_Store' },
      },
      follow_current_file = { enabled = true },
      use_libuv_file_watcher = true,
    },
    default_component_configs = {
      git_status = {
        symbols = {
          added     = '',
          modified  = '',
          deleted   = '',
          renamed   = '',
          untracked = '',
          ignored   = '',
          unstaged  = '',
          staged    = '',
          conflict  = '',
        },
      },
    },
  })
end)

-- Which-key: Shows available keybinding hints as you type
safe_setup('which-key', {})

-- Indent-blankline: Visual indent guides
safe_setup('ibl', {})

-- Autopairs: Auto-close brackets and quotes
safe_setup('nvim-autopairs', {})

-- Bufferline: IDE-style tabs for open buffers
safe_setup('bufferline', {
  options = {
    mode = 'buffers',
    diagnostics = 'coc',
    offsets = {
      { filetype = 'neo-tree', text = 'Files', text_align = 'center', separator = true },
    },
    show_close_icon = false,
    separator_style = 'slant',
  },
})

-- Flash: Jump anywhere on screen
safe_setup('flash', function(flash)
  flash.setup({})
  vim.keymap.set({ 'n', 'x', 'o' }, 's', function() flash.jump() end, { desc = 'Flash jump' })
  vim.keymap.set({ 'n', 'x', 'o' }, 'S', function() flash.treesitter() end, { desc = 'Flash treesitter select' })
end)

-- Trouble: Pretty diagnostics list
safe_setup('trouble', function(trouble)
  trouble.setup({})
  vim.keymap.set('n', '<leader>xx', '<cmd>Trouble diagnostics toggle<CR>', { desc = 'Diagnostics' })
  vim.keymap.set('n', '<leader>xd', '<cmd>Trouble diagnostics toggle filter.buf=0<CR>', { desc = 'Buffer diagnostics' })
  vim.keymap.set('n', '<leader>xt', '<cmd>Trouble todo toggle<CR>', { desc = 'TODOs' })
end)

-- Todo-comments: Highlight and search TODO/FIXME/HACK
safe_setup('todo-comments', {})

-- Web-devicons: File type icons
safe_setup('nvim-web-devicons', {})
EOF
endif

if has("gui_vimr")
  " VimR specific stuff
  set bg=dark
  set guifont=
  set lines=40
  set nu

  color dracula

  "au VimLeave * call system('echo -e -n "\033]50;StealFocus\007">'.$TTY)
  "au VimLeave * call system('echo -e -n "\033]50;StealFocus\007">'.$DISPLAY)
endif

if has("gui_macvim")
  " MacVim specific stuff
  set bg=dark
  set guioptions+=T

  set lines=40
  set nu
  set guifont=JetBrainsMono\ Nerd\ Font:h14

  let g:html_use_css=1

  color dracula

  autocmd VimEnter * call AutoNeoTree()

  "au VimLeave * call system('echo -e -n "\033]50;StealFocus\007">'.$TTY)
endif

if exists("g:neovide")
  " Neovide specific stuff
  " Use perlbrew perl if available (version-independent)
  let s:perlbrew_perl = glob('~/perl5/perlbrew/perls/*/bin/perl')
  if !empty(s:perlbrew_perl)
    let g:perl_host_prog = split(s:perlbrew_perl, "\n")[0]
  endif
  set bg=dark

  set lines=40
  set nu
  autocmd VimEnter * call AutoNeoTree()
  set nofoldenable
  let g:vim_json_syntax_conceal = 0
  set guifont=JetBrainsMonoNL\ Nerd\ Font:h14

  let g:html_use_css=1

  "nmap <D-v> "+p
  " Paste without formatting
  imap <D-v> <ESC>:set paste<CR>"+p:set nopaste<CR>i
  cmap <D-v> <C-R>+
  vmap <D-v> "+p

  " CMD+C to copy to clipboard
  vmap <D-c> "+y
  " CMD+X to cut to clipboard
  vmap <D-x> "+x
  " Select all
  nmap <D-a> gg<S-v>G

  " JetBrains-style shortcuts
  " Cmd+Shift+F — search everywhere (live grep)
  nnoremap <D-F> <cmd>Telescope live_grep<CR>
  inoremap <D-F> <ESC><cmd>Telescope live_grep<CR>
  " Cmd+P — find files (already mapped, but also from insert mode)
  inoremap <D-p> <ESC><cmd>Telescope find_files<CR>
  " Cmd+O — search for symbols/classes/functions (like Shift-Shift)
  nnoremap <D-o> <cmd>Telescope lsp_dynamic_workspace_symbols<CR>
  inoremap <D-o> <ESC><cmd>Telescope lsp_dynamic_workspace_symbols<CR>
  " Cmd+E — recent files
  nnoremap <D-e> <cmd>Telescope oldfiles<CR>
  inoremap <D-e> <ESC><cmd>Telescope oldfiles<CR>
  " Cmd+Shift+O — find symbols in current file
  nnoremap <D-O> <cmd>Telescope lsp_document_symbols<CR>
  " Cmd+N — open a new Neovide window
  nnoremap <D-n> <Cmd>call system('neovide &')<CR>

  let g:neovide_cursor_animation_length = 0
  let g:neovide_cursor_trail_size = 0
"  let g:neovide_cursor_antialiasing = v:false
  let g:neovide_cursor_animate_in_insert_mode = v:false
  let g:neovide_cursor_animate_command_line = v:false
"  let g:neovide_cursor_vfx_mode = ""
  let g:neovide_scroll_animation_length = 0
"  let g:neovide_floating_blur_amount_x = 0
"  let g:neovide_floating_blur_amount_y = 0
  let g:neovide_ligatures = v:false

  set shada='10,\"100,:20,%,n~/.local/share/nvim/shada/main.shada

  au VimLeave * sleep 100m | call system('echo -e -n "\033]50;StealFocus\007\033]1337;RequestAttention=fireworks\007">' . $TTY)

  " Jump to last position when reopening a file
  au BufReadPost * if line("'\"") > 1 && line("'\"") <= line("$") | exe "normal! g'\"" | endif

  color dracula
endif
